sudo: false

language: node

cache:
  directories:
    - sysconfcpus
    - node_modules
    - elm-stuff/build-artifacts

install:
  - source <(curl -sSL https://gist.githubusercontent.com/hkgumbs/a434d214628147955f73ff7a7ce4c22c/raw)
  - npm install elm-test elm@0.18.0

script:
  - elm2 test

before_deploy:
  - elm2 make src/Main.elm --output assets/elm.js

deploy:
  provider: pages
  local_dir: assets
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false
