language: elm
elm:
  - elm0.18.0

script:
  - elm-test

before_deploy:
  - elm make --yes src/Main.elm --output assets/elm.js

deploy:
  provider: pages
  local_dir: assets
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false
